project:
  name: swiftdeploy
  version: "1.0.0"
  contact: "soyoyeolayinka35@gmail.com"

services:
  name: swiftdeploy-app
  image: swift-deploy-1-node:latest
  port: 3000
  mode: stable
  app_version: "1.0.0"
  restart_policy: unless-stopped

nginx:
  image: nginx:latest
  port: 8080
  proxy_timeout: 10

network:
  name: swiftdeploy-net
  driver_type: bridge

logs:
  volume_name: swiftdeploy-logs

